[package]
name = "debug-matrix"
version = "0.1.0"
authors = ["MooreDev <asya.corbeau@get-moore.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
